name: sourcery
description: Reactive Magic
version: 0.2.2+1
repository: https://github.com/pstromberg98/sourcery

environment:
  sdk: ">=3.0.0 <4.0.0"

dev_dependencies:
  mocktail: ^1.0.0
  test: ^1.19.2
  very_good_analysis: ^5.1.0
